/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_silence_myclock_util_Util */

#ifndef _Included_com_example_silence_myclock_util_Util
#define _Included_com_example_silence_myclock_util_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_silence_myclock_util_Util
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_silence_myclock_util_Util_hello
  (JNIEnv *, jobject);

/*
 * Class:     com_example_silence_myclock_util_Util
 * Method:    timeStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_silence_myclock_util_Util_timeStr__
  (JNIEnv *, jobject);

/*
 * Class:     com_example_silence_myclock_util_Util
 * Method:    timeStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_silence_myclock_util_Util_timeStr__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
